### ISSUE TITLE
img.stretch gives TypeError where img.data is xarray.DataArray and img.data.data is a dask.array

### ISSUE THREAD

**Issue by gerritholl** [pytroll/trollimage#45]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import pickle
img = pickle.load(open("foo.pkl", "rb"))
img.stretch(stretch="linear")
```
[foo.pkl.gz](https://github.com/pytroll/trollimage/files/3111249/foo.pkl.gz)

#### Problem description

The attached `XRImage` contains an `xarray.DataArray` object which contains a `dask.array`.  That means, `img.data` is an `xarray.DataArray`, and `img.data.data` is a `dask.array`.  The `.stretch` method results in a `TypeError`.

#### Expected Output

I expect the `.stretch` method to be successful and the result to be as if the `xarray.DataArray` object contained a regular `numpy.ndarray` rather than a `dask.array`.

#### Actual Result, Traceback if applicable

```
Traceback (most recent call last):
  File "mwe3.py", line 3, in <module>
    img.stretch(stretch="linear")
  File "/media/nas/x21324/miniconda3/envs/py37d/lib/python3.7/site-packages/trollimage/xrimage.py", line 718, in stretch
    self.stretch_linear(**kwargs)
  File "/media/nas/x21324/miniconda3/envs/py37d/lib/python3.7/site-packages/trollimage/xrimage.py", line 780, in stretch_linear
    self.crude_stretch(left, right)
  File "/media/nas/x21324/miniconda3/envs/py37d/lib/python3.7/site-packages/trollimage/xrimage.py", line 807, in crude_stretch
    self.data -= min_stretch
  File "/media/nas/x21324/miniconda3/envs/py37d/lib/python3.7/site-packages/xarray/core/dataarray.py", line 2002, in func
    f(self.variable, other_variable)
  File "/media/nas/x21324/miniconda3/envs/py37d/lib/python3.7/site-packages/xarray/core/variable.py", line 1784, in func
    self.values = f(self_data, other_data)
TypeError: unsupported operand type(s) for -=: 'Array' and 'Array'
```
#### Versions of Python, package at hand and relevant dependencies

Trollimage `1.7.0`, Satpy `0.14.0+5.ge385d17b`, and:

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1 | packaged by conda-forge | (default, Feb 18 2019, 01:42:00)
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.12.14-lp150.12.48-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.12.0
pandas: 0.24.2
numpy: 1.16.2
scipy: 1.2.1
netCDF4: 1.5.0.1
pydap: None
h5netcdf: 0.7.1
h5py: 2.9.0
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: 1.0.22
cfgrib: None
iris: None
bottleneck: None
dask: 1.1.5
distributed: 1.26.1
matplotlib: 3.0.3
cartopy: 0.17.0
seaborn: None
setuptools: 40.8.0
pip: 19.0.3
conda: None
pytest: None
IPython: 7.4.0
sphinx: 2.0.0
```

**Comment by gerritholl** [comment]
In case there's something in the image that means it cannot be `stretch`ed, then the `.stretch(...)` method should identify that and raise an appropriate exception with an appropriate error message.

**Comment by gerritholl** [comment]
According to the [Satpy developer's guide: Migrating to xarray and dask](https://satpy.readthedocs.io/en/latest/dev_guide/xarray_migration.html#from-xarray-to-dask-and-back):

> Note dask arrays do not support in-place operations. In-place operations on xarray DataArrays will reassign the dask array automatically.

But `XRImage.crude_stretch` does attempt an in-place operation on an xarray DataArray containing a dask array:

https://github.com/pytroll/trollimage/blob/d35a7665ad475ff230e457085523e21f2cd3f454/trollimage/xrimage.py#L807-L808

which is where the stretching then fails with TypeError.

**Comment by gerritholl** [comment]
It turns out this happens not because of dask or trollimage, but because the array became an object array (which in turn happened due to https://github.com/pydata/xarray/issues/1792 earlier).
