### ISSUE TITLE
ReportError "ValueError: Merged colormap 'values' are not monotonically increasing."

### ISSUE THREAD

**Issue by drimtm** [pytroll/trollimage#87]
Python 3.7.9, satpy 0.26.0 trollimage 1.15.1. 
While testing new composite (DayNightComposite ) and 
```python
# extract from my script here

#set range for colorbar
greys.set_range(-33,30)
spectral.set_range(-73,-33)
my_cb_scale=spectral + greys


deco = [
        {'scale': {'colormap': my_cb_scale, 'extend': False,
                        'width': 900, 'height': 30,
                        'tick_marks': 5, 'minor_tick_marks': 1.0, 'cursor': [0, 690], 'bg':'white', 'bg_opacity': 127,
                        'font': '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf', 'font_size': 10,'line': 'black'}}]
                        
local_scene.save_dataset(composite, WORK + 'IRRS_'+'{start_time:%Y%m%d%H%M}.png', overlay = {**coast}, decorate = {'decorate':deco})
```
#### Error message
```
[DEBUG: 2021-10-08 10:53:34 : satpy.scene] Unloading dataset: DataID(name='colorized_ir_clouds', resolution=3000.403165817)
[DEBUG: 2021-10-08 10:53:34 : satpy.scene] Unloading dataset: DataID(name='HRV', wavelength=WavelengthRange(min=0.5, central=0.7, max=0.9, unit='µm'), resolution=1000.134348869, calibration=<calibration.reflectance>, modifiers=('sunz_corrected',))
[DEBUG: 2021-10-08 10:53:34 : satpy.scene] Unloading dataset: DataID(name='ir_sandwich', resolution=3000.403165817)
Traceback (most recent call last):
  File "/home/ilona/proj/msg/bin/draw_rss.py", line 83, in <module>
    my_cb_scale=spectral + greys
  File "/home/ilona/miniconda3/envs/env37/lib/python3.7/site-packages/trollimage/colormap.py", line 260, in __add__
    raise ValueError("Merged colormap 'values' are not monotonically "
ValueError: Merged colormap 'values' are not monotonically increasing.
```
I solved the problem by dowgrading my env to trollimage==1.14.0

**Comment by djhoese** [comment]
In cases like these what do you expect the color to be when the data is -33?

**Comment by mraspaud** [comment]
It makes sense to have equal values when merging colormaps indeed!
